### ISSUE TITLE
Log Patterns

### ISSUE THREAD

**Issue by eugenesk24** [opensearch-project/observability#850]
## Overview

We are proposing to develop an Observability feature to build a framework that surfaces auto-generated patterns in the log data to facilitate detecting outlier events and speed up troubleshooting. The first iteration of this would be implemented as an ingest time processor that would generate an additional field in the index which consists of just the punctuation signature from an event stripped of all the alphanumeric data. 

## Object Schema
patternName(Punctuation-Signature-1): User-friendly name for pattern
patternType(punctuationSignature): Type of LP
rawPattern(:...::\””): Raw pattern

## Extracting Punctuation Signature
<strike>#### Solution 1:
- Create background job
-  Punctuation signature is extracted
- Add new punctuationSignature field to all log events that consists of the id
- User lands on explorer view of a query
- A query is sent out that retrieves and aggregates data on the punctuationSignature (time, ratio, count)
- User navigates to Patterns tab
- User sees Patterns table

Pros: Process is automatic, user does not have to do anything. Once run it is completed.
Cons: No way to prioritize. User may have to wait long for the index they are actually interested in.

#### Solution 2:
- User lands on explorer view of a query
- User navigates to Patterns tab
- User clicks button to scan logs for patterns
- Punctuation signature is extracted
- Add new punctuationSignature field to those log events that consists of the id
- A query is sent out that retrieves and aggregates data on the punctuationSignature (time, ratio, count)
- User sees Patterns table

Pros: User has more control over what events are processed.
Cons: User may have to wait for extraction and be alerted when done.

#### Solution 3:
- Data is processed during ingestion using a transformation pipeline in OpenSearch ( Calls API in OpenSearch that calls pipeline to transform data )
  - Ask in opensearch-dev
- Run background job for historical data using job scheduler
  - Look at reporting to see how they generate reports
- Punctuation signature is extracted
- Add new punctuationSignature field to all log events that consists of the id
- User lands on explorer view of a query
- User navigates to Patterns tab
- User sees Patterns table

Pros: Data will be ready when it arrives in Observability.
Cons: Need background job to handle historical data. More ambiguity in how to implement.</strike>

#### Solution 4:
- PPL pattern command is used to extract pattern information and statistics during query time

## Patterns Table
![Screen Shot 2022-07-19 at 11 10 28 AM](https://user-images.githubusercontent.com/92330893/179819731-2480da05-98a1-42e9-9c9c-149cc35f759d.png)

**BASE_QUERY**: query written by user in query bar

Pattern Name: Hash puncSignature, use as id to save, use as id to query
Pattern: `BASE | patterns message | fields patterns_field`
Ratio: `[ BASE | patterns message | stats count() by patterns_field ] ÷ [ BASE | stats count() ]`
Pattern Length: .length() on pattern
Earliest Time, Recent Time, Count: `BASE | patterns message | stats count(), max(timestamp), min(timestamp) by patterns_field`

## Work Breakdown Structure
![Screen Shot 2022-07-12 at 10 28 56 AM](https://user-images.githubusercontent.com/92330893/178555426-db226a78-3b82-49f4-a7a7-bdf2ce9f6bc6.png)

#### View Log Patterns
- [x] #852 (1)
- [x] #853 (3)
- [x] #854 (3)
- [x] #888
- [x] #855 (2)
- [x] Look into changing breadcrumb trail to include query name
#### View Details of Log Patterns
- [x] #856 (5)
- [x] #857 (4)
- [x] Remove edit pencil icon from events table flyout
- [x] Add back button to flyout
- [x] Look into adding new tab when clicking see in events button
- [ ] Create new tab and name it Punctuation-Signature-1
- [ ] Change see in events to create new query
- [x] Have flyout be all the way to the top
- [x] Back on mouseover for flyout back button
- [x] "Edit name" on hover over pencil icon
- [x] Change rename flyout to just have form row
- [x] Change name to Edit name in the flyout title
- [x] Change table column to sentence case
- [x] Change event details flyout header to match the patterns tab design
- [x] Use tooltip for "Back" and "Edit name"
- [x] Change table width to maximize pattern column
- [x] Add search bar above patterns table
- [x] Change punctuation signature to generated signature
#### Sort and Filter Log Patterns
- [x] #858 (2)
- [x] #859 (4)
- [ ] Add testing

### Backend Tasks
- [x] #851
- [ ] #881
- [ ] #875

`POST ${PATTERNS_API}`

```
REQUEST_BODY
{
   patternName: "generated-signature-0001",
   patternType: "punctuationSignature",
   rawPattern: ":...::\””",
}

RESPONSE_BODY
{
  "statusCode": 200, 
  "message": "Pattern Created",
  "newPatternId: "2FG6FWGY5",
}
```
- [ ] #878

`PUT ${PATTERNS_API}`

```
REQUEST_BODY
{
   rawPattern: ':...::\””', \\ raw pattern to be renamed
   patternName: 'New-Name', \\ new name for pattern
}

RESPONSE_BODY
{
  "statusCode": 200, 
  "message": "Pattern Updated"
}
```
- [ ] #879 

`GET ${PATTERNS_API}/{patternId}`

```
RESPONSE_BODY
{
  "statusCode": 200, 
  "message": "Pattern Fetched",
  "pattern": {
      patternName: "generated-signature-0001",
      patternType: "punctuationSignature",
      rawPattern: ":...::\””",
   }
}
```
- [ ] #880

`GET ${PATTERNS_API}`

```
RESPONSE_BODY
{
  "statusCode": 200, 
  "message": "All Patterns Fetched",
  "patterns": [
      {
          patternName: "generated-signature-0001",
          patternType: "punctuationSignature",
          rawPattern: ":...::\””",
       },
       {
          patternName: "generated-signature-0002",
          patternType: "punctuationSignature",
          rawPattern: ":._;;_.[]:",
       }
   ]
}
```

**Comment by eugenesk24** [comment]
#### July 20th Worklog
- Add edit pattern flyout for rename
<img width="1768" alt="Screen Shot 2022-07-20 at 3 47 57 PM" src="https://user-images.githubusercontent.com/92330893/180096947-40daf398-0714-428a-b9d6-b56d009e32db.png">

- Add button to clear/populate data [Change table data]
![Jul-20-2022 15-59-51](https://user-images.githubusercontent.com/92330893/180096982-ef3e627b-d18e-4a37-a4c1-a8db612e0214.gif)

- Add empty table view
<img width="1792" alt="Screen Shot 2022-07-20 at 3 51 01 PM" src="https://user-images.githubusercontent.com/92330893/180097001-7a5efa8b-bfa4-420e-8745-76ee9e3d101a.png">

**Comment by eugenesk24** [comment]
**July 25th Worklog**
- Update rename flyout and add Update and Cancel buttons
<img width="1792" alt="Screen Shot 2022-07-25 at 2 42 58 PM" src="https://user-images.githubusercontent.com/92330893/180706362-f20a28dd-1a31-40b5-a1af-861bee46088d.png">

- Remove edit button from pattern detail flyout
<img width="1792" alt="Screen Shot 2022-07-25 at 2 43 17 PM" src="https://user-images.githubusercontent.com/92330893/180706376-dc0a1ac1-01ca-431a-9e6f-a8b2eb1a2c1f.png">

- Add back button, fix header style for event detail flyout
<img width="1792" alt="Screen Shot 2022-07-25 at 2 43 27 PM" src="https://user-images.githubusercontent.com/92330893/180706404-79f82bab-c653-427d-ac87-f6d92e4d9819.png">

- Use observability flyout container to unify flyout style

**Comment by eugenesk24** [comment]
**July 25th Worklog**
- Update rename flyout and add Update and Cancel buttons
<img width="1792" alt="Screen Shot 2022-07-25 at 2 42 58 PM" src="https://user-images.githubusercontent.com/92330893/180706362-f20a28dd-1a31-40b5-a1af-861bee46088d.png">

- Remove edit button from pattern detail flyout
<img width="1792" alt="Screen Shot 2022-07-25 at 2 43 17 PM" src="https://user-images.githubusercontent.com/92330893/180706376-dc0a1ac1-01ca-431a-9e6f-a8b2eb1a2c1f.png">

- Add back button, fix header style for event detail flyout
<img width="1792" alt="Screen Shot 2022-07-25 at 2 43 27 PM" src="https://user-images.githubusercontent.com/92330893/180706404-79f82bab-c653-427d-ac87-f6d92e4d9819.png">

- Use observability flyout container to unify flyout style

**Comment by eugenesk24** [comment]
**July 26th Worklog**
- Enable tool tip for "Edit name" and "Back"
<img width="1792" alt="Screen Shot 2022-07-26 at 4 29 46 PM" src="https://user-images.githubusercontent.com/92330893/180949090-4da6f0cd-8f0e-428b-9cc5-0c90ed2666b5.png">
<img width="1792" alt="Screen Shot 2022-07-26 at 4 23 29 PM" src="https://user-images.githubusercontent.com/92330893/180948937-ed7b59cd-c130-4ce0-ba89-81586c2a9c08.png">

- Match table column width to design
<img width="1792" alt="Screen Shot 2022-07-26 at 4 23 39 PM" src="https://user-images.githubusercontent.com/92330893/180948433-4fe60877-e508-4a10-8b01-9f3a194a20fd.png">

- Add search bar above patterns table
<img width="1792" alt="Screen Shot 2022-07-26 at 4 24 29 PM" src="https://user-images.githubusercontent.com/92330893/180948614-2a840eb4-015c-46e4-8647-43f66b00224d.png">

- Add Create as New Query button
<img width="1792" alt="Screen Shot 2022-07-26 at 4 24 08 PM" src="https://user-images.githubusercontent.com/92330893/180949222-16e11c1c-338b-40fe-87a5-00582335c71a.png">

- Change Punctuation-Signature-1 to generated-signature-0001
<img width="1792" alt="Screen Shot 2022-07-26 at 4 24 34 PM" src="https://user-images.githubusercontent.com/92330893/180948772-82433bdb-5989-422c-b341-922dd0d0423a.png">

**Comment by eugenesk24** [comment]
**July 27th Worklog**
- Remove Create as New Query button
<img width="1792" alt="Screen Shot 2022-07-27 at 4 16 43 PM" src="https://user-images.githubusercontent.com/92330893/181185729-a034e95b-9133-4fd6-8c9e-5bcb0b232acc.png">

- Remove View Surrounding Events button
<img width="1792" alt="Screen Shot 2022-07-27 at 4 16 51 PM" src="https://user-images.githubusercontent.com/92330893/181185739-36b98342-129f-44d8-a319-ad0498f432a8.png">

- Add saved object name to breadcrumbs
<img width="1792" alt="Screen Shot 2022-07-27 at 4 17 03 PM" src="https://user-images.githubusercontent.com/92330893/181185756-5f68c7bf-4bf0-40a0-a5f0-eb3372df4419.png">

**Comment by eugenesk24** [comment]
**July 29th Worklog**
- Removed unnecessary breadcrumbs
<img width="1792" alt="Screen Shot 2022-07-29 at 4 20 32 PM" src="https://user-images.githubusercontent.com/92330893/181705239-c43bb2a3-c4c9-49e4-b854-5df971d4ac6b.png">
<img width="1792" alt="Screen Shot 2022-07-29 at 4 20 43 PM" src="https://user-images.githubusercontent.com/92330893/181705258-dcc413e9-a79b-43f7-85ae-015b82765d88.png">
- Attempted to add selection but ran into problem with selection state control
<img width="1792" alt="Screen Shot 2022-07-29 at 4 23 03 PM" src="https://user-images.githubusercontent.com/92330893/181706051-dd7fae10-4d98-46d7-994c-c152b5d9eb2c.png">

**Comment by anirudha** [comment]
Can we move this incrementally to main. Let not wait for the final huge pr

**Comment by eugenesk24** [comment]
Patterns table has been moved to Events tab. Add ability to View and Close patterns table.
![Oct-06-2022 14-37-19](https://user-images.githubusercontent.com/92330893/194392576-9e72d44e-cbba-4c3c-aeed-3c6bfc715d1f.gif)
<img width="1667" alt="Screen Shot 2022-10-06 at 2 38 02 PM" src="https://user-images.githubusercontent.com/92330893/194392582-91e8f482-4bcb-46de-b11d-b4ee3d58ba63.png">

**Comment by nitincd** [comment]
Ideally "View Log Patterns" should be a label with an accompanying selector (combo-box?) that allows for selecting from a multiple log pattern algos.

**Comment by nitincd** [comment]
It would also be great to 
1. See sample log lines or human friendly identifier of the pattern instead of the characters that are tough to differentiate and assign meaning to.
2. Some way to compare the distribution of patterns visually
3. Send a particular pattern to the ingestion as a drop filter
4. Track one or more pattern over time to see their volume and relative distributions

**Comment by anirudha** [comment]
**Log Patterns ** 
The patterns UI analyzes your documents and groups them into common patterns, so that you can summarize your logs, identify anomalies in between logs groups over time.

**Comment by eugenesk24** [comment]
![Oct-25-2022 12-45-56](https://user-images.githubusercontent.com/92330893/197834304-c0e8560a-27ef-4458-b9cb-689030a55f8a.gif)

- Default pattern field is selected based on text field with the longest text value
- User can override default pattern field with any other text field in the sidebar
- Pattern table can now be selected to filter query results by specific pattern
- Selection can be changed by clicking a different pattern in the table
- Selection can be cleared by clicking on the **Clear Selection** button

**Comment by eugenesk24** [comment]
![Oct-26-2022 17-01-39](https://user-images.githubusercontent.com/92330893/198138269-d146640c-d4f9-4328-b202-1e98f12c9c93.gif)
- Replace pattern with sample log
